/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ScriptureLinkerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultTranslation: "ESV",
  linkService: "logos",
  showBothLinks: false,
  showRibbonIcon: true
};
var TRANSLATION_CONFIG = {
  ESV: {
    logosResource: "esv",
    logosBibleRef: "BibleESV",
    bollsCode: "ESV",
    supportsBolls: true
  },
  NASB95: {
    logosResource: "nasb95",
    logosBibleRef: "BibleNASB95",
    bollsCode: "NASB",
    supportsBolls: true
  },
  NIV: {
    logosResource: "niv2011",
    logosBibleRef: "BibleNIV",
    bollsCode: "NIV",
    supportsBolls: true
  },
  MSG: {
    logosResource: "message",
    logosBibleRef: "Bible",
    // MSG uses Bible.1Sa10.7 format
    bollsCode: "MSG",
    supportsBolls: true
  },
  LSB: {
    logosResource: "lgcystndrdbblsb",
    // LSB uses special pattern
    logosBibleRef: "BibleLSB",
    bollsCode: "LSB",
    supportsBolls: true
  },
  LEB: {
    logosResource: "leb",
    logosBibleRef: "BibleLEB",
    bollsCode: "LEB",
    supportsBolls: false
  },
  KJV: {
    logosResource: "kjv1900",
    logosBibleRef: "BibleKJV",
    bollsCode: "KJV",
    supportsBolls: true
  },
  NKJV: {
    logosResource: "nkjv",
    logosBibleRef: "BibleNKJV",
    bollsCode: "NKJV",
    supportsBolls: true
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");
var ScriptureLinkerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("p", {
      text: "Scripture linker scans your notes for bible references and converts them into clickable links for logos and bolls bible.",
      cls: "setting-item-description"
    });
    containerEl.createEl("p", {
      text: "You can use the ribbon icon or the following commands to scan your notes:",
      cls: "setting-item-description",
      attr: { style: "margin-bottom: 5px;" }
    });
    const listEl = containerEl.createEl("ul", { cls: "setting-item-description", attr: { style: "margin-top: 0;" } });
    listEl.createEl("li", { text: "Scan file for bible references" });
    listEl.createEl("li", { text: "Scan selection for bible references" });
    containerEl.createEl("br");
    new import_obsidian.Setting(containerEl).setName("Show ribbon icon").setDesc("Toggle the ribbon icon on or off").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showRibbonIcon).onChange(async (value) => {
        this.plugin.settings.showRibbonIcon = value;
        await this.plugin.saveSettings();
        this.plugin.refreshRibbonIcon();
      });
    });
    const translationSetting = new import_obsidian.Setting(containerEl).setName("Default translation").setDesc("Select the default bible translation for generated links");
    this.updateTranslationDropdown(translationSetting);
    new import_obsidian.Setting(containerEl).setName("Link service").setDesc("Choose which bible service to link to").addDropdown((dropdown) => {
      dropdown.addOption("logos", "Logos bible software (ref.ly)").addOption("bolls", "Bolls bible").addOption("both", "Both (shows two links)").setValue(this.plugin.settings.linkService).onChange(async (value) => {
        this.plugin.settings.linkService = value;
        const currentTrans = this.plugin.settings.defaultTranslation;
        const isBolls = value === "bolls" || value === "both";
        if (isBolls && !TRANSLATION_CONFIG[currentTrans].supportsBolls) {
          this.plugin.settings.defaultTranslation = "ESV";
        }
        await this.plugin.saveSettings();
        this.display();
      });
    });
    containerEl.createEl("br");
    const sponsorDiv = containerEl.createDiv();
    sponsorDiv.style.marginBottom = "10px";
    const sponsorBtn = sponsorDiv.createEl("button");
    sponsorBtn.style.display = "flex";
    sponsorBtn.style.alignItems = "center";
    sponsorBtn.style.gap = "5px";
    (0, import_obsidian.setIcon)(sponsorBtn, "heart");
    const heartIcon = sponsorBtn.querySelector("svg");
    if (heartIcon)
      heartIcon.style.color = "#db61a2";
    sponsorBtn.createSpan({ text: "Sponsor" });
    sponsorBtn.onclick = () => window.open("https://github.com/sponsors/Marvive", "_blank");
    const issuesDiv = containerEl.createDiv();
    const issuesBtn = issuesDiv.createEl("button", { text: "Report issue or feature request" });
    issuesBtn.onclick = () => window.open("https://github.com/Marvive/scripture-linker/issues", "_blank");
  }
  updateTranslationDropdown(setting) {
    const isBolls = this.plugin.settings.linkService === "bolls" || this.plugin.settings.linkService === "both";
    setting.clear();
    setting.addDropdown((dropdown) => {
      const translations = [
        { id: "ESV", name: "ESV" },
        { id: "NASB95", name: "NASB95" },
        { id: "NIV", name: "NIV" },
        { id: "KJV", name: "KJV1900" },
        { id: "NKJV", name: "NKJV" },
        { id: "MSG", name: "MSG" },
        { id: "LSB", name: "LSB" },
        { id: "LEB", name: "LEB" }
      ];
      for (const trans of translations) {
        if (isBolls && !TRANSLATION_CONFIG[trans.id].supportsBolls) {
          continue;
        }
        dropdown.addOption(trans.id, trans.name);
      }
      dropdown.setValue(this.plugin.settings.defaultTranslation).onChange(async (value) => {
        this.plugin.settings.defaultTranslation = value;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/bibleBooks.ts
var BIBLE_BOOKS = [
  // Old Testament
  { name: "Genesis", osis: "Ge", bollsId: 1, abbreviations: ["genesis", "gen", "ge", "gn"] },
  { name: "Exodus", osis: "Ex", bollsId: 2, abbreviations: ["exodus", "exod", "exo", "ex"] },
  { name: "Leviticus", osis: "Le", bollsId: 3, abbreviations: ["leviticus", "lev", "le", "lv"] },
  { name: "Numbers", osis: "Nu", bollsId: 4, abbreviations: ["numbers", "num", "nu", "nm", "nb"] },
  { name: "Deuteronomy", osis: "Dt", bollsId: 5, abbreviations: ["deuteronomy", "deut", "de", "dt"] },
  { name: "Joshua", osis: "Jos", bollsId: 6, abbreviations: ["joshua", "josh", "jos", "jsh"] },
  { name: "Judges", osis: "Jdg", bollsId: 7, abbreviations: ["judges", "judg", "jdg", "jg", "jdgs"] },
  { name: "Ruth", osis: "Ru", bollsId: 8, abbreviations: ["ruth", "rth", "ru"] },
  { name: "1 Samuel", osis: "1Sa", bollsId: 9, abbreviations: ["1 samuel", "1samuel", "1 sam", "1sam", "1 sa", "1sa", "i samuel", "i sam", "first samuel"] },
  { name: "2 Samuel", osis: "2Sa", bollsId: 10, abbreviations: ["2 samuel", "2samuel", "2 sam", "2sam", "2 sa", "2sa", "ii samuel", "ii sam", "second samuel"] },
  { name: "1 Kings", osis: "1Ki", bollsId: 11, abbreviations: ["1 kings", "1kings", "1 kgs", "1kgs", "1 ki", "1ki", "i kings", "i kgs", "first kings"] },
  { name: "2 Kings", osis: "2Ki", bollsId: 12, abbreviations: ["2 kings", "2kings", "2 kgs", "2kgs", "2 ki", "2ki", "ii kings", "ii kgs", "second kings"] },
  { name: "1 Chronicles", osis: "1Ch", bollsId: 13, abbreviations: ["1 chronicles", "1chronicles", "1 chron", "1chron", "1 chr", "1chr", "1 ch", "1ch", "i chronicles", "i chron", "first chronicles"] },
  { name: "2 Chronicles", osis: "2Ch", bollsId: 14, abbreviations: ["2 chronicles", "2chronicles", "2 chron", "2chron", "2 chr", "2chr", "2 ch", "2ch", "ii chronicles", "ii chron", "second chronicles"] },
  { name: "Ezra", osis: "Ezr", bollsId: 15, abbreviations: ["ezra", "ezr", "ez"] },
  { name: "Nehemiah", osis: "Ne", bollsId: 16, abbreviations: ["nehemiah", "neh", "ne"] },
  { name: "Esther", osis: "Es", bollsId: 17, abbreviations: ["esther", "esth", "est", "es"] },
  { name: "Job", osis: "Job", bollsId: 18, abbreviations: ["job", "jb"] },
  { name: "Psalm", osis: "Ps", bollsId: 19, abbreviations: ["psalm", "psalms", "ps", "psa", "psm", "pss"] },
  { name: "Proverbs", osis: "Pr", bollsId: 20, abbreviations: ["proverbs", "prov", "pro", "prv", "pr"] },
  { name: "Ecclesiastes", osis: "Ec", bollsId: 21, abbreviations: ["ecclesiastes", "eccl", "ecc", "ec", "qoh", "qoheleth"] },
  { name: "Song of Solomon", osis: "So", bollsId: 22, abbreviations: ["song of solomon", "song of songs", "song", "sos", "so", "canticles", "canticle", "cant"] },
  { name: "Isaiah", osis: "Is", bollsId: 23, abbreviations: ["isaiah", "isa", "is"] },
  { name: "Jeremiah", osis: "Je", bollsId: 24, abbreviations: ["jeremiah", "jer", "je", "jr"] },
  { name: "Lamentations", osis: "La", bollsId: 25, abbreviations: ["lamentations", "lam", "la"] },
  { name: "Ezekiel", osis: "Eze", bollsId: 26, abbreviations: ["ezekiel", "ezek", "eze", "ezk"] },
  { name: "Daniel", osis: "Da", bollsId: 27, abbreviations: ["daniel", "dan", "da", "dn"] },
  { name: "Hosea", osis: "Ho", bollsId: 28, abbreviations: ["hosea", "hos", "ho"] },
  { name: "Joel", osis: "Joe", bollsId: 29, abbreviations: ["joel", "joe", "jl"] },
  { name: "Amos", osis: "Am", bollsId: 30, abbreviations: ["amos", "am"] },
  { name: "Obadiah", osis: "Ob", bollsId: 31, abbreviations: ["obadiah", "obad", "ob"] },
  { name: "Jonah", osis: "Jon", bollsId: 32, abbreviations: ["jonah", "jon", "jnh"] },
  { name: "Micah", osis: "Mic", bollsId: 33, abbreviations: ["micah", "mic", "mc"] },
  { name: "Nahum", osis: "Na", bollsId: 34, abbreviations: ["nahum", "nah", "na"] },
  { name: "Habakkuk", osis: "Hab", bollsId: 35, abbreviations: ["habakkuk", "hab", "hb"] },
  { name: "Zephaniah", osis: "Zep", bollsId: 36, abbreviations: ["zephaniah", "zeph", "zep", "zp"] },
  { name: "Haggai", osis: "Hag", bollsId: 37, abbreviations: ["haggai", "hag", "hg"] },
  { name: "Zechariah", osis: "Zec", bollsId: 38, abbreviations: ["zechariah", "zech", "zec", "zc"] },
  { name: "Malachi", osis: "Mal", bollsId: 39, abbreviations: ["malachi", "mal", "ml"] },
  // New Testament
  { name: "Matthew", osis: "Mt", bollsId: 40, abbreviations: ["matthew", "matt", "mat", "mt"] },
  { name: "Mark", osis: "Mk", bollsId: 41, abbreviations: ["mark", "mrk", "mar", "mk", "mr"] },
  { name: "Luke", osis: "Lk", bollsId: 42, abbreviations: ["luke", "luk", "lk"] },
  { name: "John", osis: "Jn", bollsId: 43, abbreviations: ["john", "joh", "jhn", "jn"] },
  { name: "Acts", osis: "Ac", bollsId: 44, abbreviations: ["acts", "act", "ac"] },
  { name: "Romans", osis: "Ro", bollsId: 45, abbreviations: ["romans", "rom", "ro", "rm"] },
  { name: "1 Corinthians", osis: "1Co", bollsId: 46, abbreviations: ["1 corinthians", "1corinthians", "1 cor", "1cor", "1 co", "1co", "i corinthians", "i cor", "first corinthians"] },
  { name: "2 Corinthians", osis: "2Co", bollsId: 47, abbreviations: ["2 corinthians", "2corinthians", "2 cor", "2cor", "2 co", "2co", "ii corinthians", "ii cor", "second corinthians"] },
  { name: "Galatians", osis: "Ga", bollsId: 48, abbreviations: ["galatians", "gal", "ga"] },
  { name: "Ephesians", osis: "Eph", bollsId: 49, abbreviations: ["ephesians", "eph", "ephes"] },
  { name: "Philippians", osis: "Php", bollsId: 50, abbreviations: ["philippians", "phil", "php", "pp"] },
  { name: "Colossians", osis: "Col", bollsId: 51, abbreviations: ["colossians", "col", "co"] },
  { name: "1 Thessalonians", osis: "1Th", bollsId: 52, abbreviations: ["1 thessalonians", "1thessalonians", "1 thess", "1thess", "1 thes", "1thes", "1 th", "1th", "i thessalonians", "i thess", "first thessalonians"] },
  { name: "2 Thessalonians", osis: "2Th", bollsId: 53, abbreviations: ["2 thessalonians", "2thessalonians", "2 thess", "2thess", "2 thes", "2thes", "2 th", "2th", "ii thessalonians", "ii thess", "second thessalonians"] },
  { name: "1 Timothy", osis: "1Ti", bollsId: 54, abbreviations: ["1 timothy", "1timothy", "1 tim", "1tim", "1 ti", "1ti", "i timothy", "i tim", "first timothy"] },
  { name: "2 Timothy", osis: "2Ti", bollsId: 55, abbreviations: ["2 timothy", "2timothy", "2 tim", "2tim", "2 ti", "2ti", "ii timothy", "ii tim", "second timothy"] },
  { name: "Titus", osis: "Tt", bollsId: 56, abbreviations: ["titus", "tit", "ti"] },
  { name: "Philemon", osis: "Phm", bollsId: 57, abbreviations: ["philemon", "philem", "phlm", "phm", "pm"] },
  { name: "Hebrews", osis: "Heb", bollsId: 58, abbreviations: ["hebrews", "heb", "he"] },
  { name: "James", osis: "Jas", bollsId: 59, abbreviations: ["james", "jas", "jm"] },
  { name: "1 Peter", osis: "1Pe", bollsId: 60, abbreviations: ["1 peter", "1peter", "1 pet", "1pet", "1 pe", "1pe", "1 pt", "1pt", "i peter", "i pet", "first peter"] },
  { name: "2 Peter", osis: "2Pe", bollsId: 61, abbreviations: ["2 peter", "2peter", "2 pet", "2pet", "2 pe", "2pe", "2 pt", "2pt", "ii peter", "ii pet", "second peter"] },
  { name: "1 John", osis: "1Jn", bollsId: 62, abbreviations: ["1 john", "1john", "1 jn", "1jn", "1 jhn", "1jhn", "1 jo", "1jo", "i john", "i jn", "first john"] },
  { name: "2 John", osis: "2Jn", bollsId: 63, abbreviations: ["2 john", "2john", "2 jn", "2jn", "2 jhn", "2jhn", "2 jo", "2jo", "ii john", "ii jn", "second john"] },
  { name: "3 John", osis: "3Jn", bollsId: 64, abbreviations: ["3 john", "3john", "3 jn", "3jn", "3 jhn", "3jhn", "3 jo", "3jo", "iii john", "iii jn", "third john"] },
  { name: "Jude", osis: "Jud", bollsId: 65, abbreviations: ["jude", "jud", "jd"] },
  { name: "Revelation", osis: "Re", bollsId: 66, abbreviations: ["revelation", "revelations", "rev", "re", "rv", "apocalypse"] }
];
var abbreviationMap = null;
var cachedBookPattern = null;
function getAbbreviationMap() {
  if (abbreviationMap)
    return abbreviationMap;
  abbreviationMap = /* @__PURE__ */ new Map();
  for (const book of BIBLE_BOOKS) {
    for (const abbrev of book.abbreviations) {
      abbreviationMap.set(abbrev, book);
    }
  }
  return abbreviationMap;
}
function findBook(input) {
  const normalized = input.toLowerCase().replace(/\./g, "").trim();
  return getAbbreviationMap().get(normalized);
}
function buildBookPattern() {
  if (cachedBookPattern)
    return cachedBookPattern;
  const allNames = [];
  for (const book of BIBLE_BOOKS) {
    allNames.push(escapeRegex(book.name));
    for (const abbrev of book.abbreviations) {
      allNames.push(escapeRegex(abbrev));
    }
  }
  allNames.sort((a, b) => b.length - a.length);
  cachedBookPattern = allNames.join("|");
  return cachedBookPattern;
}
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// src/referenceParser.ts
var cachedReferenceRegex = null;
function getReferenceRegex() {
  if (cachedReferenceRegex)
    return new RegExp(cachedReferenceRegex.source, cachedReferenceRegex.flags);
  const bookPattern = buildBookPattern();
  const fullRefPattern = `(${bookPattern})\\.?\\s*(\\d{1,3})(?:[:.](\\d{1,3})(?:[-\u2013\u2014](\\d{1,3})(?:[:.](\\d{1,3}))?)?)?`;
  const shorthandRefPattern = `(?:\\()?(\\d{1,3}):(\\d{1,3})(?:[-\u2013\u2014](\\d{1,3})(?:[:.](\\d{1,3}))?)?(?:\\))?`;
  cachedReferenceRegex = new RegExp(`${fullRefPattern}|${shorthandRefPattern}`, "gi");
  return new RegExp(cachedReferenceRegex.source, cachedReferenceRegex.flags);
}
function findAllReferences(text) {
  const references = [];
  const combinedRegex = getReferenceRegex();
  let match;
  let lastBookName = null;
  let lastMatchEndIndex = 0;
  while ((match = combinedRegex.exec(text)) !== null) {
    const textSinceLastMatch = text.substring(lastMatchEndIndex, match.index);
    if (textSinceLastMatch.includes("\n")) {
      lastBookName = null;
    }
    const fullBookInput = match[1];
    let bookName = null;
    let chapter;
    let verseStart;
    let chapterEnd;
    let verseEnd;
    let rawText = match[0];
    if (fullBookInput) {
      const book = findBook(fullBookInput);
      if (!book) {
        lastMatchEndIndex = match.index + match[0].length;
        continue;
      }
      bookName = book.name;
      lastBookName = bookName;
      chapter = parseInt(match[2], 10);
      verseStart = match[3] ? parseInt(match[3], 10) : void 0;
      if (match[5]) {
        chapterEnd = parseInt(match[4], 10);
        verseEnd = parseInt(match[5], 10);
      } else {
        verseEnd = match[4] ? parseInt(match[4], 10) : void 0;
      }
    } else {
      if (!lastBookName) {
        lastMatchEndIndex = match.index + match[0].length;
        continue;
      }
      bookName = lastBookName;
      chapter = parseInt(match[6], 10);
      verseStart = parseInt(match[7], 10);
      if (match[9]) {
        chapterEnd = parseInt(match[8], 10);
        verseEnd = parseInt(match[9], 10);
      } else {
        verseEnd = match[8] ? parseInt(match[8], 10) : void 0;
      }
    }
    const beforeMatch = text.substring(0, match.index);
    const afterMatch = text.substring(match.index + match[0].length);
    let startIndex = match.index;
    let endIndex = match.index + match[0].length;
    const linkMatchBefore = beforeMatch.match(/\[$/);
    const linkMatchAfter = afterMatch.match(/^\]\(([^)]+)\)/);
    if (linkMatchBefore && linkMatchAfter) {
      const url = linkMatchAfter[1];
      if (isPluginManagedUrl(url)) {
        startIndex -= 1;
        endIndex += linkMatchAfter[0].length;
      }
    } else {
      const bothMatchAfter = afterMatch.match(/^ \(\[Logos\]\(([^)]+)\) \| \[Bolls\]\(([^)]+)\)\)/);
      if (bothMatchAfter) {
        const logosUrl = bothMatchAfter[1];
        const bollsUrl = bothMatchAfter[2];
        if (isPluginManagedUrl(logosUrl) || isPluginManagedUrl(bollsUrl)) {
          endIndex += bothMatchAfter[0].length;
        }
      }
    }
    if (startIndex === match.index && endIndex === match.index + match[0].length) {
      if (isInsideMarkdownLink(beforeMatch, afterMatch)) {
        continue;
      }
    }
    references.push({
      book: bookName,
      chapter,
      verseStart,
      chapterEnd,
      verseEnd,
      rawText,
      startIndex,
      endIndex
    });
    lastMatchEndIndex = endIndex;
  }
  return references;
}
function isPluginManagedUrl(url) {
  return url.includes("ref.ly/") || url.includes("bolls.life/");
}
function isInsideMarkdownLink(before, after) {
  const lastOpenBracket = before.lastIndexOf("[");
  const lastCloseBracket = before.lastIndexOf("]");
  const lastOpenParen = before.lastIndexOf("(");
  if (lastOpenBracket > lastCloseBracket) {
    const closeBracketParen = after.indexOf("](");
    if (closeBracketParen !== -1) {
      return true;
    }
  }
  if (lastOpenParen > lastCloseBracket && lastOpenBracket !== -1) {
    const lastCloseParen = before.lastIndexOf(")");
    if (lastOpenParen > lastCloseParen) {
      const nextCloseParen = after.indexOf(")");
      if (nextCloseParen !== -1) {
        return true;
      }
    }
  }
  return false;
}

// src/urlGenerators.ts
function generateLogosUrl(ref, translation) {
  const config = TRANSLATION_CONFIG[translation];
  const book = findBook(ref.book);
  if (!book) {
    console.warn(`Could not find book for: ${ref.book}`);
    return "";
  }
  if (translation === "LSB" || translation === "KJV") {
    let refString2 = `${book.osis}${ref.chapter}`;
    if (ref.verseStart !== void 0) {
      refString2 += `.${ref.verseStart}`;
      if (ref.chapterEnd !== void 0) {
        refString2 += `-${ref.chapterEnd}.${ref.verseEnd}`;
      } else if (ref.verseEnd !== void 0 && ref.verseEnd !== ref.verseStart) {
        refString2 += `-${ref.verseEnd}`;
      }
    }
    return `https://ref.ly/${refString2};${config.logosResource}`;
  }
  let refString = "";
  if (translation === "MSG") {
    refString = `${config.logosBibleRef}.${book.osis}${ref.chapter}`;
  } else {
    refString = `${config.logosBibleRef}.${book.osis}${ref.chapter}`;
  }
  if (ref.verseStart !== void 0) {
    refString += `.${ref.verseStart}`;
    if (ref.chapterEnd !== void 0) {
      refString += `-${ref.chapterEnd}.${ref.verseEnd}`;
    } else if (ref.verseEnd !== void 0 && ref.verseEnd !== ref.verseStart) {
      refString += `-${ref.verseEnd}`;
    }
  }
  return `https://ref.ly/logosres/${config.logosResource}?ref=${refString}`;
}
function generateBollsUrl(ref, translation) {
  const config = TRANSLATION_CONFIG[translation];
  const book = findBook(ref.book);
  if (!book) {
    console.warn(`Could not find book for: ${ref.book}`);
    return "";
  }
  let url = `https://bolls.life/${config.bollsCode}/${book.bollsId}/${ref.chapter}/`;
  if (ref.verseStart !== void 0) {
    url += `#${ref.verseStart}`;
  }
  return url;
}
function generateMarkdownLink(ref, translation, service) {
  const url = service === "logos" ? generateLogosUrl(ref, translation) : generateBollsUrl(ref, translation);
  if (!url)
    return ref.rawText;
  return `[${ref.rawText}](${url})`;
}
function generateBothLinks(ref, translation) {
  const logosUrl = generateLogosUrl(ref, translation);
  const bollsUrl = generateBollsUrl(ref, translation);
  if (!logosUrl && !bollsUrl)
    return ref.rawText;
  const links = [];
  if (logosUrl) {
    links.push(`[Logos](${logosUrl})`);
  }
  if (bollsUrl) {
    links.push(`[Bolls](${bollsUrl})`);
  }
  return `${ref.rawText} (${links.join(" | ")})`;
}

// src/main.ts
var ScriptureLinkerPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.ribbonIconEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.refreshRibbonIcon();
    this.addCommand({
      id: "scan-file",
      name: "Scan file for bible references",
      editorCallback: (editor) => {
        this.scanEditor(editor, false);
      }
    });
    this.addCommand({
      id: "scan-selection",
      name: "Scan selection for bible references",
      editorCallback: (editor) => {
        this.scanEditor(editor, true);
      }
    });
    this.addSettingTab(new ScriptureLinkerSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Refresh the ribbon icon visibility based on settings
   */
  refreshRibbonIcon() {
    if (this.settings.showRibbonIcon) {
      if (!this.ribbonIconEl) {
        this.ribbonIconEl = this.addRibbonIcon("church", "Scan file for bible references", () => {
          this.scanActiveFile();
        });
      }
    } else {
      if (this.ribbonIconEl) {
        this.ribbonIconEl.remove();
        this.ribbonIconEl = null;
      }
    }
  }
  /**
   * Scan the active file from ribbon icon click
   */
  scanActiveFile() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (view) {
      this.scanEditor(view.editor, false);
    } else {
      new import_obsidian2.Notice("No active markdown file");
    }
  }
  /**
   * Scan editor content for Bible references and replace them with links
   * @param editor The editor instance
   * @param selectionOnly Whether to scan only the selection
   */
  scanEditor(editor, selectionOnly) {
    let text;
    let startOffset = 0;
    if (selectionOnly) {
      text = editor.getSelection();
      if (!text) {
        new import_obsidian2.Notice("No text selected");
        return;
      }
      const from = editor.getCursor("from");
      startOffset = editor.posToOffset(from);
    } else {
      text = editor.getValue();
    }
    const references = findAllReferences(text);
    if (references.length === 0) {
      new import_obsidian2.Notice("No Bible references found");
      return;
    }
    const sortedRefs = [...references].sort((a, b) => b.startIndex - a.startIndex);
    let processedText = text;
    let replacementCount = 0;
    for (const ref of sortedRefs) {
      let replacement;
      if (this.settings.linkService === "both") {
        replacement = generateBothLinks(ref, this.settings.defaultTranslation);
      } else {
        replacement = generateMarkdownLink(
          ref,
          this.settings.defaultTranslation,
          this.settings.linkService
        );
      }
      const currentTextAtRange = text.substring(ref.startIndex, ref.endIndex);
      if (replacement !== currentTextAtRange) {
        processedText = processedText.substring(0, ref.startIndex) + replacement + processedText.substring(ref.endIndex);
        replacementCount++;
      }
    }
    if (selectionOnly) {
      editor.replaceSelection(processedText);
    } else {
      const cursor = editor.getCursor();
      editor.setValue(processedText);
      editor.setCursor(cursor);
    }
    new import_obsidian2.Notice(`Linked ${replacementCount} Bible reference${replacementCount === 1 ? "" : "s"}`);
  }
};
